AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - "examples/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
